---
all:
  children:
    network:
      vars:
        wireguard_interface: "wgmesh0"
        wireguard_description: "wgmesh0 managed by ansible"
        wireguard_mtu: 2840
        wireguard_subnet:
          ip: 172.16.42.0
          prefix: 24
        gre_mtu: 2816
        gre_ttl: 255
      hosts:
        hnd01br01:
          ansible_host: "2400:abcd:900d:beef::1000"
          ansible_user: "root"
          wireguard:
            endpoint: "2400:abcd:900d:beef::1000"
            port: 51820
            addresses:
              - ip: 172.16.42.1
                prefix: 32
            persistent_keepalive: 1
            private_key: "QJuN1T1Y+C72TpLPJFN/HqECpbqd+LrB1oX5r5mAfmU="
            public_key: "9ZqvzQQVyS8gr3WIOmtWIe6qOSr84+zUNx4hQoVCklk="
            psk_seed: "o+IXQBXyJXqSsVVf5/iBXrsBPuoBg677pZMP/QVmJEQ="
        hnd01br02:
          ansible_host: "2400:abcd:900d:beef::2000"
          ansible_user: "root"
          wireguard:
            endpoint: "2400:abcd:900d:beef::2000"
            port: 51820
            addresses:
              - ip: 172.16.42.2
                prefix: 32
            persistent_keepalive: 1
            private_key: "2CIN1ZG5/uiVCOtXc2VJPCDH0JF9SpQssTkklZMAZXw="
            public_key: "dCSEX0np6R2/cGflI5qt0W4tF72i5iGqb6i3cP19GSU="
            psk_seed: "sDltFS3nr3rChb/R+52ws5ipcggowK7W4gOUTpodF5A="
        nrt01br01:
          ansible_host: "2400:abcd:900d:e99::1000"
          ansible_user: "root"
          wireguard:
            endpoint: "2400:abcd:900d:e99::1000"
            port: 51820
            addresses:
              - ip: 172.16.42.128
                prefix: 32
            persistent_keepalive: 1
            private_key: "mDb8HPH6kevreCNIvQ2wAg18v1dq45BVXR2dBtiVDXM="
            public_key: "WKTbHHokCZmldJq4lmJG3xNY8EiaexEieukq37ZauXU="
            psk_seed: "eLXHPP1WxPTD6HhlpVDlWRjr9yDWzUPIQwdd3SKh3qI="
        nrt01br02:
          ansible_host: "2400:abcd:900d:e99::2000"
          ansible_user: "root"
          wireguard:
            endpoint: "2400:abcd:900d:e99::2000"
            port: 51820
            addresses:
              - ip: 172.16.42.129
                prefix: 32
            persistent_keepalive: 1
            private_key: "YEBSS/DdeYAogl8cq47YJAFxleVOFCI3hph8L52mQ3U="
            public_key: "7X6GM2D6g/v/In1U3Qd32DLCEwLHHVVFRK0wzxtZzEs="
            psk_seed: "Tvr+vcmOCmmTKaXVnmIvJ4b3zn1JiK/TdNc4sGI4xLM="
