---
all:
  children:
    network:
      children:
        gre_wireguard:
          hosts:
            tyo3br001:
              ansible_host: "{{ lookup('ansible.builtin.env', 'HOST_A_IPV6') }}"
              ansible_user: "{{ lookup('ansible.builtin.env', 'HOST_A_USER', default='root') }}"
              wireguard_interface: "{{ lookup('ansible.builtin.env', 'HOST_A_WG_INTERFACE', default='wgs2smesh0') }}"
              wireguard_description: "{{ lookup('ansible.builtin.env', 'HOST_A_WG_DESCRIPTION', default='Wireguard Connect to hnd1pve1') }}"
              wireguard_address: "{{ lookup('ansible.builtin.env', 'HOST_A_WG_ADDRESS', default='172.16.41.0/31') }}"
              wireguard_listen_port: 51820
              wireguard_peers:
                - host: hnd1pve1
                  allowed_ips: "{{ lookup('ansible.builtin.env', 'HOST_A_WG_PEER_ALLOWED_IP', default='172.16.41.1/32') }}"
              gre_interface: "{{ lookup('ansible.builtin.env', 'HOST_A_GRE_INTERFACE', default='gre2hnd1pve1') }}"
              gre_local: "{{ lookup('ansible.builtin.env', 'HOST_A_GRE_LOCAL', default='172.16.41.0') }}"
              gre_remote: "{{ lookup('ansible.builtin.env', 'HOST_A_GRE_REMOTE', default='172.16.41.1') }}"
              gre_address: "{{ lookup('ansible.builtin.env', 'HOST_A_GRE_ADDRESS', default='172.16.42.0/31') }}"

            hnd1pve1:
              ansible_host: "{{ lookup('ansible.builtin.env', 'HOST_B_IPV6') }}"
              ansible_user: "{{ lookup('ansible.builtin.env', 'HOST_B_USER', default='ubuntu') }}"
              wireguard_interface: "{{ lookup('ansible.builtin.env', 'HOST_B_WG_INTERFACE', default='wgs2smesh0') }}"
              wireguard_description: "{{ lookup('ansible.builtin.env', 'HOST_B_WG_DESCRIPTION', default='Wireguard Connect to tyo3br001') }}"
              wireguard_address: "{{ lookup('ansible.builtin.env', 'HOST_B_WG_ADDRESS', default='172.16.41.1/31') }}"
              wireguard_listen_port: 51820
              wireguard_peers:
                - host: tyo3br001
                  allowed_ips: "{{ lookup('ansible.builtin.env', 'HOST_B_WG_PEER_ALLOWED_IP', default='172.16.41.0/32') }}"
              gre_interface: "{{ lookup('ansible.builtin.env', 'HOST_B_GRE_INTERFACE', default='gre2tyo3br001') }}"
              gre_local: "{{ lookup('ansible.builtin.env', 'HOST_B_GRE_LOCAL', default='172.16.41.1') }}"
              gre_remote: "{{ lookup('ansible.builtin.env', 'HOST_B_GRE_REMOTE', default='172.16.41.0') }}"
              gre_address: "{{ lookup('ansible.builtin.env', 'HOST_B_GRE_ADDRESS', default='172.16.42.1/31') }}"
