---
- name: Install WireGuard and network tools
  ansible.builtin.apt:
    name:
      - iproute2
      - wireguard-tools
    state: present
    update_cache: true

# Prepare Systemd-Networkd

- name: Create systemd-networkd configuration directory
  ansible.builtin.file:
    path: /etc/systemd/network
    state: directory
    owner: root
    group: root
    mode: "0755"

# WireGuard

## Generate Private Key

- name: Store WireGuard Private Key
  ansible.builtin.copy:
    content: "{{ wireguard.private_key }}\n"
    dest: "/etc/systemd/network/{{ wireguard_interface }}.key"
    owner: root
    group: systemd-network
    mode: "0640"

- name: Store Wireguard Public Key
  ansible.builtin.copy:
    content: "{{ wireguard.public_key }}\n"
    dest: "/etc/systemd/network/{{ wireguard_interface }}.pub"
    owner: root
    group: systemd-network
    mode: "0640"

- name: Store Wireguard Pre Shared Key Seed
  ansible.builtin.copy:
    content: "{{ wireguard.psk_seed }}\n"
    dest: "/etc/systemd/network/{{ wireguard_interface }}.psk.seed"
    owner: root
    group: systemd-network
    mode: "0640"

- name: Store WireGuard Peer Pre Shared Keys
  ansible.builtin.copy:
    content: |
      {%- set peer = hostvars[peer_host] -%}
      {%- set wireguard_l_psk_seed = wireguard.psk_seed if inventory_hostname < peer_host else peer.wireguard.psk_seed -%}
      {%- set wireguard_r_psk_seed = wireguard.psk_seed if inventory_hostname >= peer_host else peer.wireguard.psk_seed -%}
      {{ lookup("ansible.builtin.pipe", "
      {
          printf '%s' " ~ (wireguard_l_psk_seed | quote) ~ " | base64 -d
          printf '%s' " ~ (wireguard_r_psk_seed | quote) ~ " | base64 -d
      } | sha256sum | awk '{print $1}' | xxd -r -p | base64
      ") }}
    dest: "/etc/systemd/network/{{ wireguard_interface }}-{{ peer_host | regex_replace('[^A-Za-z0-9_.-]', '_') }}.psk"
    owner: root
    group: systemd-network
    mode: "0640"
  loop: "{{ ansible_play_hosts_all | difference([inventory_hostname]) }}"
  loop_control:
    loop_var: peer_host

- name: Configure WireGuard netdev
  ansible.builtin.template:
    src: wireguard.netdev.j2
    dest: "/etc/systemd/network/10-{{ wireguard_interface }}.netdev"
    owner: root
    group: systemd-network
    mode: "0640"

- name: Configure WireGuard network
  ansible.builtin.template:
    src: wireguard.network.j2
    dest: "/etc/systemd/network/10-{{ wireguard_interface }}.network"
    owner: root
    group: systemd-network
    mode: "0640"

- name: Restart systemd-networkd
  ansible.builtin.systemd_service:
    name: systemd-networkd
    state: restarted
